app {
  name = "MultiSourceDataCleaning"
}

spark {
  app_name = "MultiSourceDataCleaning"
  master = "spark://spark-master:7077"
  shuffle_partitions = 8
  default_parallelism = 8
  log_level = "WARN"
}

jdbc {
  url = "jdbc:postgresql://postgres:5432/tp_multisource"
  driver = "org.postgresql.Driver"
  user = "postgres"
  password = "postgres"

  customers_table = "public.customers"
  orders_table = "public.orders"
  order_items_table = "public.order_items"
  products_table = "public.products"
}

mongodb {
  uri = "mongodb://admin:admin@mongo:27017/?authSource=admin"
  database = "tp_multisource"
  collection = "reviews"
}

paths {
  delivery_events = "data/delivery_events/"
  output_root = "data/output/"
  customer_order_360 = "data/output/customer_order_360/"
  quality_report = "data/output/data_quality_report/"
  rejects = "data/output/rejects/"
}

reference {
  currencies = ["EUR", "USD", "GBP", "MAD"]
}